# Generated by Django 5.0.4 on 2024-04-12 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditems',
            name='stock',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='custom_user',
            name='phone',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
    ]
