# Generated by Django 5.0.4 on 2024-04-13 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_rename_fooditem_cart_food_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='quantity',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=3),
        ),
    ]
