# Generated by Django 5.0.4 on 2024-04-13 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_order_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('paid', 'Paid'), ('cod', 'Cash On Delivery')], default='', max_length=20),
        ),
    ]
