# Generated by Django 5.0.4 on 2024-04-13 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_order_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Order picked', 'Order Picked'), ('Out For Delivery', 'Out For Delivery'), ('Delivered', 'Delivered')], max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Cash On Delivery', 'Cash On Delivery')], default='', max_length=20),
        ),
    ]
